version: '3'
services:

  # zookeeper:
  #   image: mesoscloud/zookeeper:3.4.6-ubuntu-14.04
  #   hostname: "zookeeper"
  #   container_name: zookeeper
  #   ports:
  #     - "2181:2181"
  #     - "2888:2888"
  #     - "3888:3888"

  mesos-master:
    image: zulli73/mesos-master:1.8.0
    hostname: "mesos-master"
    container_name: master
    privileged: true
    environment:
      - MESOS_HOSTNAME=mesos-master
      # - MESOS_CLUSTER=SMACK
      # - MESOS_QUORUM=1
      # - MESOS_ZK=mesos://zookeeper:2181/mesos
      - MESOS_LOG_DIR=/tmp/mesos/logs
    # links:
      # - zookeeper
    ports:
      - "5050:5050"

  mesos-slave-1:
    image: zulli73/mesos-slave:1.8.0
    hostname: "mesos-slave-1"
    container_name: slave-1
    privileged: true
    environment:
      - MESOS_HOSTNAME=mesos-slave-1
      - MESOS_PORT=5151
      - MESOS_MASTER=mesos://mesos:5050
    links:
      # - zookeeper
      - mesos-master
    ports:
      - "5151:5151"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  mesos-slave-2:
    image: zulli73/mesos-slave:1.8.0
    hostname: "mesos-slave-2"
    container_name: slave-2
    privileged: true
    environment:
      - MESOS_HOSTNAME=mesos-slave-2
      - MESOS_PORT=5152
      - MESOS_MASTER=mesos://master:5050
    links:
      # - zookeeper
      - mesos-master
    ports:
      - "5152:5152"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  
  zeppelin:
    image: zulli73/mesos-spark-zeppelin:mesos-1.8.0-spark-2.4.3-zeppelin-0.8.1
    hostname: "mesos-zeppelin"
    container_name: zeppelin
    environment:
      # - MASTER=zk://zookeeper:2181/mesos
      - MASTER=mesos://mesos-master:5050
      # - MASTER: spark://master:7077
      #spark://master:7077
      # - VIRTUAL_HOST: ${LETS_HOST}
      # - LETSENCRYPT_HOST: ${LETS_HOST}
      # - LETSENCRYPT_EMAIL: ${LETS_EMAIL}
    links:
      # - zookeeper
      - mesos-master
    ports:
      - 8080:8080    